### PR TITLE
Update LiveConnect

### PR DESCRIPTION
**Pull request by 3link**
This PR updates LiveConnect and introduces a default Ajax timeout.

Related PRs:
- https://github.com/LiveIntent/prebid.github.io/pull/17

### CODE REVIEW

**Review by peixunzhang — APPROVED** [review]

**Review by wi101 — APPROVED** [review]

**Comment by wi101** [comment]
Consider to change this
https://github.com/prebid/Prebid.js/blob/master/modules/userId/index.js#L99

**Review by SuperIzya — APPROVED** [review]

**Comment by 3link** [comment]
> Consider to change this https://github.com/prebid/Prebid.js/blob/master/modules/userId/index.js#L99

I think this is the general Prebid user id module doc. I would leave it as is.

**Comment by 3link** [comment]
Alternatively, we could have two `ajaxTimeout`s - one for the resolution and one for the collector in `liCollectConfig`. That probably would be even cleaner. I will push a commit soon.

**Comment by 3link** [comment]
> Alternatively, we could have two `ajaxTimeout`s - one for the resolution and one for the collector in `liCollectConfig`. That probably would be even cleaner. I will push a commit soon.

Done in 9f6e02b819d233945f00d5884e0e04bbfaafed7c. The behaviour is now as follows:
- if the [timeout for resolution](https://github.com/prebid/Prebid.js/blob/master/modules/userId/index.js#L99) is not provided, a default is used
- if the [timeout for collection](https://github.com/LiveIntent/prebid.github.io/pull/17/files#diff-25cff37b723196e1559e925406f16b54c507f0a20fe263b952058f2c4166b35cR135) is not provided, a default is used

**Review by mschuwalow — APPROVED** [review]

**Pull request closed without merging**
